### ISSUE TITLE
Provide alternative to renv for setup

### ISSUE THREAD

**Issue by kgostic** [seabbs/cste-forecasting-workshop#1]
In case people don't know how to use GitHub, might want to provide setup instructions that don't depend on cloning the repo to run run [renv::restore()](https://github.com/seabbs/cste-forecasting-workshop/blob/main/epinow2.Rmd#L30).

- [ ] Provide a .zip file containing the repo contents. Provide instructions for how to download the .zip, open the .Rproj file, and run renv::restore(), probably as a .pdf or a readme?
- [ ] Provide a short description near [Line 30)[https://github.com/seabbs/cste-forecasting-workshop/blob/main/epinow2.Rmd#L30] of what renv::restore() is doing. E.g.:

"renv::restore()" is a command that will automatically load or install the correct versions of all packages needed to run this analysis.

**Comment by zsusswein** [comment]
Add some signposting to explain what renv is doing and why we're using it

**Comment by zsusswein** [comment]
And then check that everything runs! 

Do some data exploration, find a state that works better maybe? or is a little less weird?
