### ISSUE TITLE
What rendered format are we targetting? 

### ISSUE THREAD

**Issue by seabbs** [seabbs/cste-forecasting-workshop#11]
Html or markdown? 

Somethings work in one but not the other so we should decide.

**Comment by seabbs** [comment]
I've assumed its html and so optimised for that.

**Comment by kgostic** [comment]
I think that's the best way to go. I don't think most of the audience will know how to use GitHub, so I doubt that the .md will get much attention.

I think most people will download a .zip file and work from there.
