### ISSUE TITLE
Add prompt to install renv if not already present

### ISSUE THREAD

**Issue by kgostic** [seabbs/cste-forecasting-workshop#14]
Did a clean run and realized this would be an issue.

**Comment by zsusswein** [comment]
At least for me, it installed itself when I started the rproj in a clean environment

**Comment by kgostic** [comment]
Ah, I didn't open the .Rproj first. Went right to the script, which others will probably do too. 

I think it's worth having a failsafe. Do you agree Sam and Zack?

**Comment by seabbs** [comment]
I think we would ideally have them in the working directory but having a fail safe doesn't really hurt (but maybe the fail safe is to direct them to have their r session running in the directory vs anything else as could otherwise have other impacts maybe).
