### ISSUE TITLE
Suggestions for further work

### ISSUE THREAD

**Issue by seabbs** [seabbs/cste-forecasting-workshop#17]
Do we want some suggestions/questions for keen beans? 

Do we want to use this as a fact finding exercise and write some kind of poll (like which aspect of this tutorial is most useful, what is missing, what confuses you etc,)

**Comment by kgostic** [comment]
I like this idea, but let's revisit on Friday?

**Comment by seabbs** [comment]
Added keen bean stuff. I thinnk the isuer poll is a good idea but makinng another issue for this.
