### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by seabbs** [seabbs/cste-forecasting-workshop#21]
Can we host them im the repo as a pdf so this is a complete tutorial?

**Comment by seabbs** [comment]
It would be nice if the tutorial linked back to the slides to reinforce ideas etc

**Comment by kgostic** [comment]
I think I can do this but have to check on clearance. I'll upload the .pdf if allowed!

**Comment by seabbs** [comment]
@kgostic added some signposting to the tutorial based on the slides (liked them a lot).
