### ISSUE TITLE
Arguably "this plot is empty" because the model didn't converge...

### ISSUE THREAD

**Issue by kgostic** [seabbs/cste-forecasting-workshop#26]
...not because there are no delays.

I want to use this as a teachable moment: sometimes our tools can't do everything. We have to make an expert judgement and proceed anyway.

**Comment by seabbs** [comment]
That isn't true in this instance and the model has converged (albeit with issues)?

**Comment by zsusswein** [comment]
Not disagreeing with your expert opinion Sam, but when this is all over I'd love if we could make some time for you to talk me through this a bit. I generally have alarm bells going off when there are this many divergences even when adapt_delta is cranked up.

You have a ton of experience with these models and I'm sure you have a good set of heuristics that make you comfortable anyway -- I'd love to get a sense of them. You're back the first week of July?

**Comment by seabbs** [comment]
The issue is because there is essentially no truncation in the time period considered. That leaves the mean going from small negatives to -Inf -> numerical instability -> divergent transitions. Its the kind of model misspecification warning flag Dts are there for

**Comment by seabbs** [comment]
I'm back on the 10th of July though arriving at 5.50 in the morning.

**Comment by seabbs** [comment]
I need to see what my cal looks like over the next few weeks but will generally be reachable on emai/github and may be able to squeeze some meetings in.

**Comment by seabbs** [comment]
I've added a little table that shows the empirical reporting rates for the first available delay to help guide people here.

**Comment by seabbs** [comment]
I am not planning on adding anything else here as I think this covered so going to close unless anyone else has something to add?
