### ISSUE TITLE
Get github pages working

### ISSUE THREAD

**Issue by zsusswein** [seabbs/cste-forecasting-workshop#28]
@seabbs -- I see you have the github action to build and deploy, but I'm hitting a 404 [here](https://samabbott.co.uk/cste-forecasting-workshop/).

I'm not totally sure where the issue is -- seems like you have the index and whatnot in the build action?

**Comment by seabbs** [comment]
Just debugging the actions now (see the actions tab for the failed builds). Two exciting issues so far: 1. Can't spell README; 2. Forgot pandoc.
