### ISSUE TITLE
User poll

### ISSUE THREAD

**Issue by seabbs** [seabbs/cste-forecasting-workshop#29]
User poll questionaire exploring how they found the tutorial and/or the kinds of tools they would find useful.

**Comment by kgostic** [comment]
Do you have a preferred tool to use here Sam, or do you want us to come up with something?

**Comment by seabbs** [comment]
I like this thing alot (attaching an example): https://pol.is/report/r64ajcsmp9butzxhzj44c

The more I think about this maybe its just a nightmare because of the whole gov angle

**Comment by seabbs** [comment]
Shall I leave this with @kgostic to decide on/implement as you want?

**Comment by seabbs** [comment]
(or just close out)
