### ISSUE TITLE
link to paper in README is broken

### ISSUE THREAD

**Issue by kylieainslie** [seabbs/cste-forecasting-workshop#38]
The link to the paper: _Practical considerations for measuring the effective reproductive number, Rt_ in the last section of README.Rd is broken

**Comment by seabbs** [comment]
Thanks @kylieainslie. Fixed in [b5563d9](https://github.com/seabbs/cste-forecasting-workshop/commit/b5563d9a628f5eba1c6f436724b03e6392c32f59)
