### ISSUE TITLE
Add wrapper function around states

### ISSUE THREAD

**Issue by zsusswein** [seabbs/cste-forecasting-workshop#7]
We need a function that takes a vector of states and outputs faceted plots.

This should generalize the Ohio example and guide us toward a single state to do the rest of the analysis with. It will, hopefully, match our intuition on what's common.

**Comment by zsusswein** [comment]
@seabbs -- have you already done this one?

**Comment by seabbs** [comment]
Yes though not with a function - I was very lazy.
